import { DynamoDBClient, PutItemCommand, DeleteItemCommand, UpdateItemCommand } from '@aws-sdk/client-dynamodb';
import { DynamoDBDocumentClient, ScanCommand, UpdateCommand } from '@aws-sdk/lib-dynamodb';

const client = new DynamoDBClient({});
const dynamo = DynamoDBDocumentClient.from(client);

// Scan function to retrieve all tasks
export const getAllTasks = async () => {
  const params = { 
    TableName: 'recipes' 
  };
  const data = await dynamo.send(new ScanCommand(params));
  console.log("inside method", data);
  return data.Items;
};

// Add task function to insert a new task
export const addTask = async (task) => {
    const cid = Math.random().toString(36).substring(2, 15);
  const params = {
    TableName: 'recipes',
    Item: {
      id: cid,        // Unique ID for the task (e.g., generated by the client or UUID)
      name: task.name,    // Task name (or other properties you may have)
      status: task.status  // Task status (e.g., "pending", "completed")
    }
  };

  try {
    await dynamo.send(new PutItemCommand(params));
    return { success: true, message: 'Task added successfully!' };
  } catch (error) {
    console.error('Error adding task:', error);
    return { success: false, message: 'Error adding task' };
  }
};

// Update task function
export const updateTask = async (taskId, newTask) => {
  const params = {
    TableName: 'recipes',
    Key: { id: taskId },
    UpdateExpression: 'SET #name = :name, #status = :status',
    ExpressionAttributeNames: {
      '#name': 'name',
      '#status': 'status',
    },
    ExpressionAttributeValues: {
      ':name': newTask.name,
      ':status': newTask.status,
    },
    ReturnValues: 'UPDATED_NEW',
  };

  try {
    await dynamo.send(new UpdateItemCommand(params));
    return { success: true, message: 'Task updated successfully!' };
  } catch (error) {
    console.error('Error updating task:', error);
    return { success: false, message: 'Error updating task' };
  }
};

// Delete task function
export const deleteTask = async (taskId) => {
  const params = {
    TableName: 'recipes',
    Key: { id: taskId }
  };

  try {
    await dynamo.send(new DeleteItemCommand(params));
    return { success: true, message: 'Task deleted successfully!' };
  } catch (error) {
    console.error('Error deleting task:', error);
    return { success: false, message: 'Error deleting task' };
  }
};

// Lambda handler function
export const handler = async (event) => {
  const method = event.httpMethod; // Get the HTTP method (GET, POST, etc.)
  const body = event.body ? JSON.parse(event.body) : null;
  const taskId = event.pathParameters ? event.pathParameters.id : null;

  if (method === 'GET') {
    try {
      const tasks = await getAllTasks();
      return {
        statusCode: 200,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "Tasks retrieved successfully",
          tasks: tasks,
        }),
        isBase64Encoded: false,
      };
    } catch (error) {
      return {
        statusCode: 500,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "Error fetching tasks",
          error: error.message,
        }),
        isBase64Encoded: false,
      };
    }
  }

  if (method === 'POST') {
    try {
      const result = await addTask(body); // Call the addTask function
      return {
        statusCode: 201,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(result),
        isBase64Encoded: false,
      };
    } catch (error) {
      return {
        statusCode: 500,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "Error adding task",
          error: error.message,
        }),
        isBase64Encoded: false,
      };
    }
  }

  if (method === 'PUT' && taskId) {
    try {
      const result = await updateTask(taskId, body);  // Update task by ID
      return {
        statusCode: 200,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(result),
        isBase64Encoded: false,
      };
    } catch (error) {
      return {
        statusCode: 500,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "Error updating task",
          error: error.message,
        }),
        isBase64Encoded: false,
      };
    }
  }

  if (method === 'DELETE' && taskId) {
    try {
      const result = await deleteTask(taskId);  // Delete task by ID
      return {
        statusCode: 200,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(result),
        isBase64Encoded: false,
      };
    } catch (error) {
      return {
        statusCode: 500,
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          message: "Error deleting task",
          error: error.message,
        }),
        isBase64Encoded: false,
      };
    }
  }

  return {
    statusCode: 405,
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      message: 'Method Not Allowed',
    }),
    isBase64Encoded: false,
  };
};
